### ISSUE TITLE
Probleem met dubbele activiteiten

### ISSUE THREAD

**Issue by Jille** [karpenoktem/kninfra#102]
Issue:
>  Op http://kn.cx/activiteit/  staat de Middeleeuwse maaltijd nog bij "Activeiten" ipv bij "Oude activiteiten" maar ik kan hem ook niet sluiten (hij lijkt al gesloten te zijn.) 

Mogelijk onderliggend probleem:
> Ja, dat klopt, die activiteit bestond 2x. Ik weet ook niet precies hoe/waarom, maar ik had er volgens mij een keer wat aan veranderd en toen een nieuwe aangemaakt omdat het hele idee veranderd was enzo, maar toen waren beide activiteiten precies hetzelfde. Als iemand zich voor de ene aanmeldde, kwam 'ie vanzelf ook in de lijst bij die andere te staan enzo.  

Mogelijke oorzaak:
> Ah. Misschien wordt bij het hernoemen van activiteiten niet gecheckt of die naam al bestaat?

**Comment by aykevl** [comment]
Net getest, dit is nog steeds een probleem. Je kunt 2 activiteiten met dezelfde naam aanmaken.
