### ISSUE TITLE
secr: Nieuwe leden automatisch een gegevenscontrolemailtje sturen

### ISSUE THREAD

**Issue by Jille** [karpenoktem/kninfra#116]

**Comment by aykevl** [comment]
Is dit issue gefixt?

**Comment by bwesterb** [comment]
Dacht het wel... ik snap niet waarom hij nog open staat.

**Comment by aykevl** [comment]
Aan de commits hierboven te zien is het gefixt, dus ik denk dat hij dicht kan.
