### ISSUE TITLE
Duidelijk maken wat een onbevestigde aanmelding betekent

### ISSUE THREAD

**Issue by thundur** [karpenoktem/kninfra#152]
Het is onduidelijk wat een onbevestigde aanmelding precies betekent. Het is wel nodig dat dit duidelijk wordt zodat systemen die voortbouwen op de inschrijvingen (debiteuren, reservelijstsysteem) weten hoe ze zo'n aanmelding moeten beschouwen.

**Comment by aykevl** [comment]
Volgens mij mag dit wel gesloten worden.
