### ISSUE TITLE
Genitief in subscriptions-bevestiging-mail

### ISSUE THREAD

**Issue by spr3nk3ls** [karpenoktem/kninfra#179]
https://github.com/karpenoktem/kninfra/blame/3ce264001cb2d2e626dfe44f83213a329566029d/kn/subscriptions/forms.py#L29

Daar hoort 'Simons opmerkingen waren', 'Sanne's opmerkingen waren' of 'Felix' opmerkingen waren' te staan.

https://onzetaal.nl/taaladvies/advies/bezits-s-algemene-regels

**Comment by aykevl** [comment]
Dit is ondertussen gefixt, dus mag gesloten worden:

> Je opmerkingen waren:

**Comment by aykevl** [comment]
Dit is ondertussen gefixt. Bovendien is het nogal lastig om dit te doen. Het hangt af van de uitspraak en van de laatste lettergreep (als je weet waar de laatste lettergreep begint kun je het in de meeste gevallen goed doen):
https://nl.wikipedia.org/wiki/Apostrof_in_de_Nederlandse_spelling#Genitief
