### ISSUE TITLE
Thumbnail uitgerekt bij gedraaide foto

### ISSUE THREAD

**Issue by bwesterb** [karpenoktem/kninfra#272]
Ik heb net een van de foto's gedraaid en zag dat de thumbnail de verkeerde verhouding krijgt.

https://kn.cx/fotos/2014-11-13-foutefeest/astrid#IMG_0059.JPG

**Comment by aykevl93** [comment]
Ik denk dat het een caching issue is. Bij mij staat hij wel goed.

Het zijn hier trouwens wel foutefeestfoto's die je online zet. Ik denk niet dat dat de bedoeling is (ook al zijn het thumbnails, mensen zijn net herkenbaar).

**Comment by bwesterb** [comment]
Ik dacht dat deze thumbnail wel kon, maar omdat jij denkt van niet heb ik hem maar weggehaald. Als dit slechts een cache dingetje is, dan is het prima.  (Kunnen we niet een `?rot=` achter de thumbnail zetten of (iets algemener) een `?ver=` met een oplopend versienummer.)

**Comment by aykevl93** [comment]
Versienummers lijken me alleen maar onhandig naar mijn mening. Dan moet je meer *state* bijhouden en dat wil je zo min mogelijk. Rotatie wordt al bijgehouden en dat is wat ik gebruik als je een foto draait en dan opslaat (dan wordt de geroteerde foto opgehaald van de server). Ik kan dit systeem overal gaan gebruiken.
Het is niet perfect (het levert minder schone URLs) op, maar wel praktisch.
Ik kan er eens naar kijken, maar het heeft voor mij geen hele hoge prioriteit.

**Comment by bwesterb** [comment]
Het heeft inderdaad lage prioriteit.
