### ISSUE TITLE
Voer wijzigingen aan planning automatisch door

### ISSUE THREAD

**Issue by aykevl** [karpenoktem/kninfra#281]
Dus bijvoorbeeld dat leden van de groep tappers automatisch worden toegevoegd aan de lijst en weer worden verwijderd uit de lijst.

**Comment by aykevl93** [comment]
Ik zie dat er aparte collections worden bijgehouden voor de planning, waarbij de mensen die ingepland kunnen worden staan in `planning_workers`. Waarom worden daarvoor niet de desbetreffende lijsten gebruikt, namelijk `barco`, `bestuur`, `cocks`, `draai` en `tappers`? Dan hoeven die wijzigingen niet handmatig doorgevoerd te worden.

Een andere oplossing zou zijn om in `update_db` die lijsten met elkaar te vergelijken en eventueel `planning_workers` daarop aan te passen. Dat zou niet zoveel werk zijn.

Overigens, waarom, *waarom*, staan voorkeuren voor bepaalde diensten in de code??? Zie https://github.com/karpenoktem/kninfra/blob/master/kn/planning/score.py#L101. Dat vind ik echt heel smerig. Naar mijn mening is dit iets dat daar echt niet hoort, maar in de database zou moeten en door de secretaris en de desbetreffende planner aangepast zou moeten kunnen worden.

**Comment by bwesterb** [comment]
Jille en Bram hebben de planning software geschreven, dus wat ik er nu over zeg zijn slechts gokken.  Ik denk dat ze aparte pools hebben omdat ze het lelijk vonden bij groepen of gebruikers extra informatie in het JSON object te zetten.  Dat is voor mij geen bezwaar: dat is juist het grote voordeel van de flexibiliteit van Mongo.

Ik zou de updates niet in `update_db` uitvoeren, maar in een aparte thread ná `update_db`.  Alle andere taken wachten namelijk totdat `update_db` klaar is en worden parallel daarna uitgevoerd.

Ik vind de gehardcode scores ook lelijk, maar waarschijnlijk kostte dat domweg minder moeite om te schrijven dan een interface.

**Comment by aykevl93** [comment]
Ja, ik vond het er al een beetje SQL-achtig uitzien, en dat werkt niet goed met MongoDB.

Misschien ga ik dit nog een keertje fixen, maar het heeft een lage prioriteit voor mij. Ik zou zeggen, wie wil kan het oppakken.
