### ISSUE TITLE
Smoelen roteren aan de hand van EXIF informatie

### ISSUE THREAD

**Issue by aykevl** [karpenoktem/kninfra#299]
Uploads worden nu niet automatisch geroteerd op basis van EXIF informatie.

Zie http://www.imagemagick.org/script/command-line-options.php#auto-orient (dan moet ook de EXIF informatie gestript worden bij foto's, via `-strip`).

**Comment by bwesterb** [comment]
Zo te zien leest hij al wel EXIF uit in `kn.fotos`.  Is het niet een kwestie van dan direct de rotatie erop aan te passen?

**Comment by bwesterb** [comment]
(`Foto.update_metadata`)

**Comment by aykevl** [comment]
Dit gebeurt niet via `kn.fotos`. In `kn.fotos` doen we het handmatig omdat we foto's daar zelf willen roteren. Dat is hier niet nodig.

**Comment by aykevl** [comment]
Ik heb net naar de code gekeken.
Nu wordt PIL (`Image`) gebruikt voor het converteren van de foto's. We kunnen natuurlijk het uitlezen van de rotatie in een aparte functie zetten. We kunnen ook ImageMagick gebruiken, maar ik weet niet wat de bedoeling was van `default_storage`. Het zou namelijk eenvoudig zijn om gewoon [`.path`](https://docs.djangoproject.com/en/1.8/ref/files/storage/#django.core.files.storage.Storage.path) te gebruiken voor ImageMagick (die dus `-auto-orient` heeft).
De tweede optie is denk ik het eenvoudigst.

**Comment by bwesterb** [comment]
Wij houden zelf een rotatie bij.  Dat is rotatie ten opzichte van het bronbestand.  Is het dus niet eenvoudiger als we de EXIF rotatie zelf uitlezen.  We lezen al de EXIF tags uit in `update_metadata`, dus wat we moeten doen is daarna de rotatie afhankelijk daarvan te zetten.  Als we `convert`s auto-orient zouden gebruiken, dan krijg je verwarrend gedrag als we hem overschrijven met onze eigen rotatie: bijv.: de gebruiker klikt "draai naar rechts", maar hij draait dan 180 graden.  Of mis ik iets?

**Comment by bwesterb** [comment]
Wat betreft `default_storage`: wat vind je er raar aan?  Dat was toen de code geschreven werd de standaard manier om het te doen.  Misschien is het nu weer veranderd.  Wat zou ji dan precies voorstellen  Ik begrijp je verwijzing naar `.path` niet.

**Comment by aykevl** [comment]
> Wij houden zelf een rotatie bij. Dat is rotatie ten opzichte van het bronbestand. Is het dus niet eenvoudiger als we de EXIF rotatie zelf uitlezen.

Nee. Dit doen we in `kn.fotos`, maar niet in het smoelenboek. Daar is het niet eens mogelijk de rotatie te veranderen. In `kn/leden/*` wordt nergens gerefereerd naar `update_metadata`.

`default_storage.path(name)` is een functie die we zouden kunnen gebruiken om het echte path te krijgen voor ImageMagick.

**Comment by bwesterb** [comment]
Oeps, ik las helemaal over "smoel" heen – ik dacht direct dat het over het fotoboek ging.

Maar je schreef: je weet niet wat de bedoeling was van `default_storage`?

**Comment by aykevl** [comment]
Done.
