### ISSUE TITLE
Focus on username field on login

### ISSUE THREAD

**Issue by dsprenkels** [karpenoktem/kninfra#303]
Add autofocus on username field on login page.

(http://www.w3schools.com/tags/att_input_autofocus.asp)

**Comment by bwesterb** [comment]
:)

**Comment by dsprenkels** [comment]
In mijn browser is dit niet een fix.

N.b. `autofocus` op het input element zetten is lang niet zat, omdat een gebruiker altijd eerst op het inlogknopje zal klikken (en dus focus over zal dragen). Hier zal sowieso wat javascript aan te pas moeten komen.

Deze issue gaat dan ook over de https://karpenoktem.nl/accounts/login/ pagina, niet over het algemene inlogknopje.

**Comment by mrngm** [comment]
Ja, wat je nu gerevert hebt was ook mijn 'eerste fix'. Dat ben ik voornamelijk niet verder mee gegaan omdat het niet werkte ([zie ook deze comment in mijn fork](https://github.com/mrngm/kninfra/commit/1c5a67c14d1ce4c9c2de972ef3468729af465033#commitcomment-15043050)). Focus bij het algemene inlogknopje is ietwat ingewikkelder.
