### ISSUE TITLE
Forum / Stukken redirect to other domain name

### ISSUE THREAD

**Issue by mrngm** [karpenoktem/kninfra#304]
When logged in on, for example, `kn.cx`, the menu links in https://kn.cx/smoelen/ for `Forum` and `Stukken` redirect to another domain name: `https://karpenoktem.nl/<path>`

**Comment by bwesterb** [comment]
Waarom is dit een probleem?

**Comment by aykevl** [comment]
Dit is eigenlijk een feature: op een dev installatie blijven die links werken. Maar het is eenvoudig aan te passen in settings.py via `EXTERNAL_URLS` (dat zouden dan host-relatieve links moeten zijn zoals `/forum/`).

**Comment by mrngm** [comment]
@bwesterb je moet opnieuw inloggen.

**Comment by aykevl** [comment]
Gaan we dit fixen?

**Comment by bwesterb** [comment]
We zouden ervoor kunnen zorgen dat alle URLs normaliseren naar `karpenoktem.nl`.

**Comment by aykevl** [comment]
Bedoel je dat ze allemaal daarnaar redirecten? Daar zou ik wel heel erg voorstander van zijn. Het gebeurt me nu vaak genoeg dat ik een link volg, maar zie dat ik opnieuw moet inloggen omdat hij bijvoorbeeld op kn.cx staat, of www.karpenoktem.nl. We hebben nu 6 hostnames, die allemaal gebruiken (zonder redirects) lijkt me wat veel.

**Comment by dsprenkels** [comment]
Ik ben ook expliciet voor.

**Comment by bwesterb** [comment]
Dit is gefixt op lighttpd (maar nog niet in salt).
