### ISSUE TITLE
Activiteiten blijven niet lang genoeg op de agenda staan

### ISSUE THREAD

**Issue by bwesterb** [karpenoktem/kninfra#309]
Zolang een activiteit (waarschijnlijk) nog bezig is, zou die op de agenda moeten blijven staan.

**Comment by bwesterb** [comment]
@aykevl ?

Bijvoorbeeld: nachtpick is al van de agenda af.

![screen shot 2015-07-07 at 21 57 07](https://cloud.githubusercontent.com/assets/9975/8555869/2ade1c18-24f3-11e5-9cba-c6261f0fbcbb.png)

**Comment by mrngm** [comment]
Is dit hetzelfde issue als met de planning (dagoverschrijdende zaken), of louter de weergave?

**Comment by aykevl** [comment]
Ik heb ooit ingebouwd dat oude activiteiten niet meer worden weergegeven. "Oud" is hier na de eindtijd, in het geval van de nachtpicknick 00:00 uur. Veel activiteiten gaan in de agenda maar tot 23:59, waardoor je dus dit probleem krijgt.
Een eenvoudige oplossing zou zijn om er, zeg, 4 uur bij op te tellen en ze dus pas weg te halen om 04:00. Of ze niet meer automatisch weg te laten gaan.

**Comment by aykevl** [comment]
Ter referentie:
https://github.com/karpenoktem/kninfra/blob/master/kn/agenda/entities.py#L15

**Comment by aykevl** [comment]
Oh, ik zie nu dat hij zelfs kjjkt naar het *begin* van de activiteit. Dat is natuurlijk niet de bedoeling.

**Comment by bwesterb** [comment]
Ah, een regressie.  Fix je het?

**Comment by aykevl** [comment]
Is dit gefixt?

**Comment by bwesterb** [comment]
Ik ben het probleem niet meer tegengekomen... dus ik ga uit van wel.
