### ISSUE TITLE
Webserverpoorten staan niet open op IPv6

### ISSUE THREAD

**Issue by mrngm** [karpenoktem/kninfra#316]
Er is een IPv6-adres voor (www.)karpenoktem.nl, maar deze geeft een connection refused.

Is te fixen in (we draaien geen lighttpd meer?) nginx, alleen die configfiles kan ik niet vinden in de repo.

**Comment by bwesterb** [comment]
We draaien nog lighttpd (totdat alles is overgezet naar de nginx config die wel onder `salt` staat).

Zou nu gefixt moeten zijn?

**Comment by mrngm** [comment]
Jep, werkt. Thanks.

**Comment by aykevl** [comment]
Alleen de DNS server heeft nog geen IPv6.
https://internet.nl/site/karpenoktem.nl/results#
