### ISSUE TITLE
Fix 404 bij hernoemen activiteit

### ISSUE THREAD

**Issue by aykevl** [karpenoktem/kninfra#332]
Op dit moment is het mogelijk de korte naam van activiteiten te veranderen. Daarmee wordt de oude URL ongeldig. Dit kan op twee manieren opgelost worden:

* verbied het veranderen van de korte naam (laat het invoer veldje weg bij bewerken)
* houd de verandering bij en doe een 301 redirect

**Comment by bwesterb** [comment]
Of gewoon meerdere namen per activiteit, zoals entiteiten dat ook hebben.
