### ISSUE TITLE
annuleren werkt niet bij wijzigen naam entiteit

### ISSUE THREAD

**Issue by bwesterb** [karpenoktem/kninfra#333]
Als de prompt voor de nieuwe naam van een entiteit geannuleerd wordt, wordt de naam onterecht alsnog veranderd naar, naar het lijkt, de lege string.

**Comment by bwesterb** [comment]
Deze was gefixt, hè?

**Comment by aykevl** [comment]
Ik heb niet echt Safari dus kan het lastig testen. Maar de pull request hiervoor is gemergd (#340).
