### ISSUE TITLE
Foto's werken niet in een andere taal

### ISSUE THREAD

**Issue by aykevl** [karpenoktem/kninfra#411]
De foto's laden niet, en het switchen tussen talen geeft gekke kruimelpaden.

**Comment by aykevl** [comment]
Nog niet helemaal: https://karpenoktem.nl/nl/fotos/

**Comment by bwesterb** [comment]
Bij mij werkt het?

**Comment by aykevl** [comment]
Het kruimelpad werkt nog niet helemaal:
![screenshot-5](https://cloud.githubusercontent.com/assets/729697/21613887/89524e3a-d1d7-11e6-81ff-6c428ad92053.png)

**Comment by aykevl** [comment]
Gefixt.
