### ISSUE TITLE
mediawiki is niet ondersteund door Debian Jessie

### ISSUE THREAD

**Issue by bwesterb** [karpenoktem/kninfra#421]
`mediawiki` was nog een package voor Debian squeeze, maar is [niet meer ondersteund op jessie](http://unix.stackexchange.com/questions/287761/mediawiki-support-has-been-dropped-in-debian-stable-jessie-whats-the-alterna).

We moeten de installatiecode in saltstack aanpassen: nu faalt saltstack omdat het het pakket `mediawiki` niet kan vinden.

**Comment by aykevl** [comment]
Beetje offtopic, maar dit vind ik wel een beetje overdreven:

> The only alternative I can think of is to go back to the dark ages of system administration (before stable/LTS Linux distributions were invented), subscribe to the mediawiki-announce mailing list and install *every. single. security update.* manually. As you can imagine, I'd like to avoid that.

Wat ik een tijdje heb gedaan, was dat ik MediaWiki via git had gedownload, plus extensies die nodig waren, en met elke security update runde ik een script dat simpelweg `git pull` runde voor MediaWiki + elke extensie. Werkte erg goed. Ik denk dat het zelfs geautomatiseerd zou kunnen worden door dat script elke nacht via cron te runnen.

**Comment by mrngm** [comment]
Een van de antwoorden:

> This didn't happen yesterday. This happened back in 2014, when the people who *were* responsible for packaging up mediawiki for Debian simply stopped doing so.

Verder kreeg de package `mediawiki` al sinds juni 2016 geen security-updates meer.

Ik heb zo'n mediawiki-upgrade eigenlijk altijd handmatig gedaan, *juist* omdat de `mediawiki` package zo hopeloos achterliep. Heeft Saltstack ondersteuning voor custom scripts?

**Comment by bwesterb** [comment]
Ja, het zou ook via custom scripts kunnen.  Dat moet dan wel gedaan worden :).
