### ISSUE TITLE
planning: het verleden bekijken

### ISSUE THREAD

**Issue by awesterb** [karpenoktem/kninfra#434]
Het is bijvoorbeeld handig voor de penningmeester en kasco om voorgaande indelingen van de tappers op de borrel te kunnen bekijken.

**Comment by aykevl** [comment]
Hoever terug wil je dan kijken?
Je kunt prima oude planningen laten zien, maar *alle* oude planningen laten zien is erg veel. Je kunt het bijvoorbeeld voor de afgelopen periode doen (1 maand, 1 jaar, ...).

**Comment by awesterb** [comment]
Twee jaar, want het werk van de kasco van jaar N is waarschijnlijk klaar aan het eind van jaar N+1, maar een <select> voor de te tonen maand kan dit probleem ook oplossen.

**Comment by aykevl** [comment]
Ik zie net dat dit al mogelijk is: door de `lookbehind` parameter toe te voegen.
Bijvoorbeeld: https://karpenoktem.nl/planning/?lookbehind=356
Zie: https://github.com/karpenoktem/kninfra/commit/73a847b1ad585c0b3e7e9395d4bcc45105eac8bb
Maar dit mag wel wat gebruikersvriendelijker vind ik :)
