### ISSUE TITLE
Giedo werkt niet meer

### ISSUE THREAD

**Issue by awesterb** [karpenoktem/kninfra#448]
Tijdens een `vagrant up` (na een `vagrant destroy`) blijft de zaak hangen op:

 > [DEBUG] Fetching file from saltenv 'base', ** attempting ** 'salt://sankhara/initializeDb'
 > [DEBUG   ] No dest file found
 > [INFO    ] Fetching file from saltenv 'base', ** done ** 'sankhara/initializeDb'
 > [INFO    ] Fetching file from saltenv 'base', ** done ** 'sankhara/initializeDb', mode set to 0644
 > [INFO    ] Executing command '/tmp/tmppVqqN_ database' in directory '/root'
 > [ERROR   ] {'pid': 9628, 'retcode': 2, 'stderr': "python: can't open file  '/root/repo/salt/sankhara/initializeDb.py': [Errno 2] No such file or directory", 'stdout': ''}
 > [INFO    ] Completed state [Initialize database] at time 19:53:51.995901 duration_in_ms=91.589
 > [INFO    ] Running state [giedo-sync && touch /home/infra/.initial-giedo-sync-run
 > ] at time 19:53:51.996099
 > [INFO    ] Executing state cmd.run for giedo-sync && touch /home/infra/.initial-giedo-sync-run
 > [INFO    ] Executing command 'giedo-sync && touch /home/infra/.initial-giedo-sync-run
' as user 'infra' in directory '/home/infra'

**Comment by bwesterb** [comment]
Deze fout heb ik gefixt in de `hans` branch.
