### ISSUE TITLE
'Sponsoring' pagina

### ISSUE THREAD

**Issue by yorickvP** [karpenoktem/kninfra#520]
> Is het mogelijk om onder 'over' een tabblad 'sponsoring' toe te voegen? 
> Dit geeft de vereniging namelijk een aantal mogelijkheden voor zaken die een verwijzing op de website vragen, zonder dat dit direct heel opdringerig op belangrijke pagina's staat.

**Comment by JVerbeek** [comment]
[Ziehier](https://github.com/karpenoktem/kninfra/tree/sponsorpagina)
