### ISSUE TITLE
Foto's website

### ISSUE THREAD

**Issue by yorickvP** [karpenoktem/kninfra#521]
>B16 heeft een aantal foto's uitgezocht ter vervanging van de huidige foto's in de slideshow op de website. Kunnen jullie die voor ons vervangen? 
>Als het goed is zijn ze al in de correcte afmetingen (gebaseerd op de verhoudingen van het op de website afgebeelde frame). 
>
>Als ik iets kan/moet doen om te helpen (of dit ergens gewoon zelf kan), dan hoor ik dat natuurlijk graag!

Zie ook #519

**Comment by yorickvP** [comment]
De foto's in kwestie staan in de mail.

**Comment by JVerbeek** [comment]
Kan ik vnv wel doen, dit lijkt me niet moeilijk

**Comment by JVerbeek** [comment]
Okay, het was niet eergisteravond maar zie branch 521-fotos-website, kn/static/media/slideshow.

**Comment by JVerbeek** [comment]
Nu ik dit daadwerkelijk kan testen ga ik ermee verder, het werkt namelijk nog niet
